#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re
import sys

md_skip = False
rfced_remove = False
for line in sys.stdin:
    # Strip newline
    line = line.rstrip()

    # Strip the kramdown-rfc2629 attribution line
    if re.search(r'<!-- generated by', line):
        continue

    # Remove unnecessary whitespace in tags
    line = re.sub(r' +/>', '/>', line)
    line = re.sub(r' +>', '>', line)

    # Fix smart quotes
    line = re.sub(r'“', '"', line)
    line = re.sub(r'”', '"', line)
    line = re.sub(r'‘', "'", line)
    line = re.sub(r'’', "'", line)

    # Fix smart dashes
    line = re.sub(r'–', "--", line)

    # Fix smart ellipses
    line = re.sub(r'…', "...", line)

    # Strip Markdown-source
    if not md_skip:
        md_skip = re.match(r'<!-- ##markdown-source:', line)
    if md_skip:
        md_skip = not re.match(r'-->', line)
        continue
        
    # Strip the kramdown-rfc2629 credit
    if re.match(r'<!-- generated by ', line):
        continue

    print line
