#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re
import sys

md_skip = False
rfced_remove = False
for line in sys.stdin:
    # Strip newline
    line = line.rstrip()

    # Fix xml header lines
    line = re.sub(r'encoding="UTF-8"', 'encoding="US-ASCII"', line)
    line = re.sub(r'<!-- generated by', '<!-- originally generated by', line)

    # Fix smart quotes
    line = re.sub(r'“', '"', line)
    line = re.sub(r'”', '"', line)
    line = re.sub(r'‘', "'", line)
    line = re.sub(r'’', "'", line)

    # Strip Markdown-source
    if not md_skip:
        md_skip = re.match(r'<!-- ##markdown-source:', line)
    if md_skip:
        md_skip = not re.match(r'-->', line)
        continue
        
    # Strip the kramdown-rfc2629 credit
    if re.match(r'<!-- generated by ', line):
        continue

    print line
